

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu al
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Android SDK kur
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Debug APK derle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: :app:assembleDebug

      - name: Debug APK'yı yükle (Eserler)
        uses: actions/upload-artifact@v4
        with:
          name: HoloViral-debug-apk
          path: app/build/outputs/apk/debug/*.apk
